#!/bin/bash

# Colors (adjust these for your preference)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

# Message
MESSAGE="$BLUE Happy Holi $RED to my $YELLOW linkedin $GREEN network $RESET"

# Print the message with colors
echo -e "$MESSAGE"

exit 0
